spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mopl-mysql-dev.cd8oe2q2qsl0.ap-northeast-2.rds.amazonaws.com:3306/mopl_dev?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_DEV_USER}
    password: ${MYSQL_DEV_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST_DEV}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_DEV}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

logging:
  level:
    root: INFO
    org.hibernate.sql: DEBUG