server:
  port: 8081

spring:
  main:
    web-application-type: none
  application:
    name: mopl-batch
  profiles:
    include: core
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      dev: core-dev
      prod: core-prod

  batch:
    job:
      enabled: false

tmdb:
  base-url: https://api.themoviedb.org/3
  token: ${TMDB_API_TOKEN}
