plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':mopl-core')

    // web
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'

    // jwt
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    // oauth2
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client'

    // swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.0'

    // actuator
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // DevTools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // AWS S3
    implementation platform("software.amazon.awssdk:bom:2.26.21")
    implementation "software.amazon.awssdk:s3"
    implementation "software.amazon.awssdk:sts"

    // MapStruct
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
}