server:
  port: 8082

spring:
  application:
    name: mopl-chat
  profiles:
    active: prod
    include: core
    group:
      dev: core-dev
      prod: core-prod
      test: core-test
      local: core-local

  kafka:
    consumer:
      group-id: chat-server-group # 채팅 서버용 그룹 id

#jwt
jwt:
  access-secret: ${JWT_ACCESS_SECRET}