server:
  port: 8080

spring:
  application:
    name: mopl-api
  profiles:
    include: core
    active: dev
    group:
      dev: core-dev
      prod: core-prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# swagger
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    persist-authorization: true

#jwt
jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-token-validity: 900000      # 15분 (밀리초)
  refresh-token-validity: 604800000  # 7일 (밀리초)
