name: CD mopl-batch (develop)

on:
  push:
    branches:
      - develop
    paths:
      - "mopl-core/**"
      - "mopl-batch/**"
      - "build.gradle"
      - "settings.gradle"
      - "gradle/**"
      - "gradlew"
      - ".github/workflows/cd-mopl-batch.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build & Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mopl-batch
          IMAGE_TAG: release-${{ github.run_number }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -f mopl-batch/Dockerfile .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG